:toc: macro

= RFC 1: T Staking Contract

:icons: font
:numbered:
toc::[]

== Proposal

=== Goal

The goal of this proposal is to specify a simple and secure stake delegation
mechanism. It should enable T owners to have their wallets offline and their
stake operated by operators on their behalf. All off-chain client software
should be able to run without exposing operator’s private key and should not
require any owner’s keys at all. The stake delegation should also optimize the
network throughput without compromising the security of the owners’ stake.

This proposal aims at implementing a minimum viable staking contract version
allowing to support legacy KEEP and NU stakes, as well as native T delegations
in all applications developed against this staking contract version.
It means that all stakers, no matter of the type of their stake (legacy KEEP,
legacy NU, liquid T) will be able to participate in all applications developed
against this staking contract version on equal rules.
The functionality of the staking contract can be further extended by the
upgradeability of the contract code.

=== Terminology

Owner:: An address owning T tokens and tokens that could be converted to
T: KEEP, NU, including grants. An owner is the ultimate holder of the tokens.
Before stake delegation, the owner has full control over the tokens, and the
tokens are returned to the owner after stake delegation has finished.
Owner’s participation is not required in the day-to-day operations on the
stake, so cold storage can be accommodated to the maximum extent.

Operator:: An address of a party authorized to operate in the network on behalf
of a given owner. The operator handles the everyday operations on the delegated
stake without actually owning the staked tokens. An operator can not simply
transfer away delegated tokens, however, it should be noted that the operator’s
misbehavior may result in slashing tokens and thus the entire staked amount is
indeed at stake.

Beneficiary:: An address where the rewards for participation are sent, earned by
the operator, on behalf of the owner. A beneficiary doesn’t sign or publish any
protocol-relevant transactions, but any currency or tokens earned by the
operator will be transferred to the beneficiary.

Authorizer:: An address appointed by an owner to authorize applications on
behalf of the owner. An application must be approved by the authorizer before the
operator is eligible to participate.

Delegated stake:: An owner’s staked tokens, delegated to the operator by the
owner. Delegation enables token owners to have their wallets offline and their
stake operated by operators on their behalf.

Application:: An external smart contract or a set of smart contracts utilizing
functionalities offered by Threshold Network. Example applications are: random
beacon, proxy re-encryption, and tBTC. Applications authorized for the given
operator are eligible to slash the stake delegated to that operator.

== Specification

=== Functionality

==== Delegating a stake

Tokens are delegated by the owner. During the delegation, the owner needs to
appoint an operator, beneficiary, and authorizer. The owner may decide to
delegate just a portion of their tokens. The owner may delegate multiple times
to different operators. For simplicity, the operator address can not be reused
between delegations even if all tokens have been unstaked. To protect against 
griefing by frontrunning stake delegation transactions and reserving operator
addresses, staking contract should require a governable minimum stake amount for 
each delegation and there should be a minimum undelegation delay of 24 hours.

Staking contract binds the owner with the operator, beneficiary, and authorizer
for the given stake delegation and records the stake delegation amount.

Existing KEEP and NU stake owners also need to perform a delegation so that T
staking contract can record their operator, beneficiary, and authorizer. Since
these values are read-only, they should be copied from KEEP staking contract to
T staking contract and NU stakers should set them during the delegation. For
existing stakes, the entire amount staked in the legacy contract is cached in T
staking contract. Caching amount staked in the legacy staking contract helps to 
identify discrepancy between staking contracts. It is much easier to just compare
two values instead of checking authorization of every application (see Keeping
information in sync section).

==== Authorizing an application

Before the operator is eligible to participate in the given application, the
authorizer appointed during the stake delegation needs to review the application
and approve it to use the stake. From the moment of approval, the application
is authorized to slash or seize the stake.

The authorizer decides up to which amount the given application is eligible to
slash. This allows managing the risk profile of the staker individually for each
application. The authorized stake amount can be increased and decreased.

The amount authorized is set individually for each application and should be
used as a staker's weight in the application: for work selection and rewards.
The amount authorized for the application can be decreased as a result of
the application approving authorization decrease request.
The amount authorized for the application can be also decreased as a result of
slashing, including slashing executed in the context of another application. 

The application being authorized is notified via a callback every single time
new authorization happens and the application may decide to revert the
transaction if individual requirements of the application are not met.
For example, application may require a certain minimum authorized amount.
The application is notified every single time the authorization increases or
decreases. The application can revert this transaction in case some rules
specific to that application are not met. Inside the callback, the application
can also update its internal state, such as, for example, the weight of the
operator in the sortition pool.

Authorization decrease is a two-step process. First, the authorizer requests to
decrease the authorization, and the application is notified about it by
a callback. In the second step, the application approves the decrease at its own
discretion. It is up to every individual application to decide if and when the
authorization decrease gets approved. New authorization decrease request
overwrites the pending one.

All applications first need to be authorized in a registry of T applications
controlled by the governance before any authorizer can use them.
To protect against the attack of blocking the slashing queue by exceeding the
block gas limit for slashing the particular operator, there should be a
governable limit of applications that can be authorized per operator.

==== Stake top-up

Top-up increases the amount of tokens locked in a delegation and allows to later
increase the authorization for applications. This increases the probability of being
chosen for work in the application but is only effective for future checks of the
authorized amount.

Top-ups can be executed for native T stakes and for legacy KEEP/NU stakes.

Native T stakers can only top-up their stakes with a liquid T.

Existing KEEP and NU stakers wanting to execute a top-up have two options. One
option is to wrap their KEEP/NU to T and then, execute a top-up in T staking
contract. The second option is to execute a top-up in their legacy staking
contracts and notify T staking contract about the fact their legacy stake
increased.

Effectively, it means that existing KEEP stakers can mix their legacy KEEP
stakes with liquid T stakes. Similarly, existing NU stakers can mix their legacy
NU stakes with liquid T stakes. This functionality adds some complexity to the
staking contract but it puts existing KEEP/NU stakers in the same spot as new T
stakers. Without it, existing stakers would not be able to top-up their stakes
with T earned from operating in the network, so they would be in a worse spot
than new T stakers allowed to top-up their stakes using earned T and this way
increasing their rewards.

The owner or operator can execute a stake top-up for an operator using a liquid T. 
Stake top-up does not automatically increase authorization levels for applications.
Stake top-up is a one-step process and does not require any delay.

==== Undelegating a stake (unstaking)

The owner or operator may decide to unstake some amount of tokens if the amount
left on the stake after this operation will be higher or equal to the highest
authorization amongst all applications. Even if all tokens have been unstaked,
relationship between owner, operator, beneficiary, and authorizer is retained
in the staking contract in case some applications still have some rewards
waiting for withdrawal.

It is possible to change the composition of the staked amount by unstaking
legacy tokens or by unstaking liquid T tokens. This allows existing KEEP/NU
stakers to unstake their legacy stakes one day while still being able to operate
in T network and earning rewards.

If the owner or operator attempts to unstake tokens before 24 hours passed since
the delegation so that the amount left in the contract would be below the
minimum stake, the transaction reverts.

It is expected that full unstaking is first completed on T staking contract before
full unstaking on a legacy staking contract for the given operator gets initiated.

==== Keeping information in sync

To avoid expensive calls to legacy staking contract, it is assumed that cached
information in T staking contract about the amount staked in the legacy contract
is always up-to-date.

T staking contract should expose a function allowing to seize some amount of T
from the operator in case that operator has a lower active stake
(eligible for work selection) in the old staking contract than the amount cached
in T staking contract. 5% of the amount seized is given to the person who
notified about the discrepancy and the rest is burned. The amount is a
governable parameter and can be updated at any time by the governance, with no
governance delay. The transaction notifying about stake amounts not being in sync
needs to update authorizations of all affected applications and execute an
involuntary authorization decrease on each affected application.

For legacy stakers, staked amount can become out-of-sync in three cases:

* stake undelegated on the legacy contract,
* stake topped-up on the legacy contract,
* stake slashed on the legacy contract.

It is expected that stake undelegation will be first performed on T staking
contract and then on the legacy staking contract.

It is expected that a top-up will be first performed on the legacy staking
contract, and then propagated to the new staking contract, in the same
transaction. Even if it does not happen in the same transaction, this kind of
discrepancy is not slashable given that the stake amount on the legacy contract
is higher than the stake amount on T staking contract.

In case the stake has been slashed on the legacy contract, the operator is
required to update their information on T staking contract as soon as possible.
In practice, for Keep, with the random beacon disabled, and tBTC v1 slashing the 
stake only in case of a proven fraud that had to be committed by all operators of
ECDSA keep, this approach is acceptable.

An integral part of the staking contract should be a bot or process inside an
off-chain client monitoring stakes and notifying about discrepancies. This is
especially important given that the bot may need to voluntarily inform about
discrepancies for operators that have been already slashed to zero.

Owner or operator can decrease the legacy contract active stake cached amount on
T staking contract if no application has authorization higher than the liquid T
stake. It allows to undelegate from the legacy staking contract while still
being able to operate in T network and earning rewards.

==== Slashing a stake

Authorized applications can slash or seize a stake. Slash operation decreases
the stake of an operator and burns slashed tokens. Seize decreases the stake,
burns 95% of the stake, and awards up to 5% to the notifier of misbehavior.

To keep stakes synchronized between applications when operators are slashed,
without the risk of running out of gas, the staking contract queues up slashings
and let users process the transactions.

When an application slashes one or more operators, it adds them to the slashing
queue on the staking contract. A queue entry contains the operator's address and
the amount they're due to be slashed.

When there is at least one operator in the slashing queue, any account can
submit a transaction processing one or more operators' slashings, and collecting
a reward for doing so. A queued slashing is processed by updating the operator's
stake to the post-slashing amount, updating authorized amount for each
affected application, and notifying all affected applications that
the operator's authorized stake has been reduced due to slashing. The
application must then do the necessary adjustments, such as removing the
operator from the sortition pool or reducing its weight, changing the operator's
eligibility for rewards, and so forth.

Every application callback executed as a result of a slash should have a 250k gas
limit. Slashing are processed in a FIFO basis, and there is just one function
exposed by the staking contract allowing to slash one or more operators from the
head of the queue. Callback failure does not revert the transaction. In case
the callback failed, the slashing request is removed from the queue and never
retried so it is in the application's best interest to ensure it can always
execute the callback. The same happens if the slash operation fails because
the given operator has insufficient stake to slash.

In the case of legacy stakers, their liquid T is slashed first before a call to 
the legacy contract is executed.

It is important to note slashing executed in the context of one application may
lead to involuntarily decreasing the authorization for other applications in 
case the amount of stake available after the slashing is lower than these
authorizations.

=== Upgradeability

The staking contract will be upgradeable. The exact upgradeability mechanism is
out of the scope of this document.

== Public API

=== Delegating a stake

==== `stake(address operator, address beneficiary, address authorizer, uint96 amount) external` 
   
Creates a delegation with `msg.sender` owner with the given operator,
beneficiary, and authorizer. Transfers the given amount of T to the staking
contract. The owner of the delegation needs to have the amount approved to
transfer to the staking contract.

==== `stakeKeep(address operator) external`

Copies delegation from the legacy KEEP staking contract to T staking contract.
No tokens are transferred. Caches the active stake amount from KEEP staking 
contract. Can be called by anyone.

==== `stakeNu(address operator, address payable beneficiary, address authorizer) external`

Copies delegation from the legacy NU staking contract to T staking contract,
additionally appointing beneficiary and authorizer roles. Caches the amount
staked in NU staking contract. Can be called only by the original delegation
owner.

==== `refreshKeepStakeOwner(address operator) external onlyOwnerOf(operator)`

Refresh Keep stake owner. Can be called only by the old owner.

==== `setMinimumStakeAmount(uint96 amount) external onlyGovernance`

Allows the governance to set the minimum required stake amount. This amount is
required to protect against griefing the staking contract and individual
applications are allowed to require higher minimum stakes if necessary.  

=== Authorizing an application

==== `approveApplication(address application) external onlyGovernance`

Allows the governance to approve the particular application before individual
stake authorizers are able to authorize it.

==== `increaseAuthorization(address operator, address application, uint96 amount) external onlyAuthorizerOf(operator)`

Increases the authorization of the given operator for the given application by
the given amount. Calls `authorizationIncreased(address operator, uint96 amount)`
callback on the given application to notify the application. Can only be called
by the given operator's authorizer.

==== `requestAuthorizationDecrease(address operator, address application, uint96 amount) external onlyAuthorizerOf(operator)`

Requests decrease of the authorization for the given operator on the given
application by the provided amount. Calls `authorizationDecreaseRequested(address operator, uint96 amount)`
on the application. It does not change the authorized amount. Can only be called
by the given operator's authorizer. Overwrites pending authorization decrease
for the given operator and application.

==== `requestAuthorizationDecrease(address operator) external onlyAuthorizerOf(operator)`

Requests decrease of all authorizations for the given operator on all 
applications by all authorized amount. Calls `authorizationDecreaseRequested(address operator, uint256 amount)`
for each authorized application. It may not change the authorized amount immediatelly. 
When it happens depends on the application. Can only be called by the given operator’s 
authorizer. Overwrites pending authorization decrease for the given operator and 
application.

==== `approveAuthorizationDecrease(address operator) external onlyRequestedApplication returns (uint96)`

Called by the application at its discretion to approve the previously requested
authorization decrease request. Can only be called by the application that
was previously requested to decrease the authorization for that operator.
Returns resulting authorized amount for the application.

==== `forceDecreaseAuthorization(address operator, address application) external`

Decreases the authorization for the given `operator` on the given disabled 
`application`, for all authorized amount. Can be called by anyone.

==== `pauseApplication(address application) external onlyPanicButtonOf(application)`

Pauses the given application's eligibility to slash stakes. Besides that stakers can't
change authorization to the application. Can be called only by a panic button of the 
particular application. The paused application can not slash stakes until it is 
approved again by the governance using `approveApplication` function. Should be 
used only in case of an emergency.

==== `disableApplication(address application) external onlyGovernance`

Disables the given application. The disabled application can't slash stakers. Also 
stakers can't increase authorization to that application but can decrease without 
waiting by calling `forceDecreaseAuthorization` at any moment. Can be called only 
by the governance. The disabled application can't be approved again. Should be used 
only in case of an emergency.

==== `setPanicButton(address application, address panicButton) external onlyGovernance`

Sets the panic button role for the given application to the provided address.
Can only be called by the governance. If the panic button for the given
application should be disabled, the role address should be set to 0x0 address.

==== `setAuthorizationCeiling(uint256 ceiling) external onlyGovernance`

Sets the maximum number of applications one operator can authorize. Used to
protect against DoSing slashing queue. Can only be called by the governance.

=== Stake top-up

==== `topUp(address operator, uint96 amount) external onlyOwnerOrOperator(operator)`

Increases the amount of the stake for the given operator. The sender of this
transaction needs to have the amount approved to transfer to the staking
contract. Can be called only by the owner or operator.

==== `topUpKeep(address operator) external onlyOwnerOrOperator(operator)`

Propagates information about stake top-up from the legacy KEEP staking contract
to T staking contract. Can be called only by the owner or operator.

==== `topUpNu(address operator) external onlyOwnerOrOperator(operator)`

Propagates information about stake top-up from the legacy NU staking contract
to T staking contract. Can be called only by the owner or operator.

=== Undelegating a stake (unstaking)

==== `unstakeT(address operator, uint96 amount) external onlyOwnerOrOperator(operator)`

Reduces the liquid T stake amount by `amount` and withdraws `amount` of T 
to the owner. Reverts if there is at least one authorization higher than the sum
of a legacy stake and remaining liquid T stake or if the `amount` is higher than
the liquid T stake amount. Can be called only by the owner or operator.

==== `unstakeKeep(address operator) external onlyOwnerOrOperator(operator)`

Sets the legacy staking contract active stake amount cached in T staking
contract to 0. Reverts if the amount of liquid T staked in T staking contract is
lower than the highest application authorization. This function allows to
unstake from Keep staking contract and sill being able to operate in T network
and earning rewards based on the liquid T staked. Can be called only by the
delegation owner and operator.

==== `unstakeNu(address operator, uint96 amount) external onlyOwnerOrOperator(operator)`

Reduces cached legacy NU stake amount by `amount`. Reverts if there is at least
one authorization higher than the sum of remaining legacy NU stake and liquid T
stake for that operator or if amount is higher than the cached legacy stake
amount. If succeeded, the legacy NU stake can be partially or fully undelegated
on the legacy staking contract. This function allows to unstake from NU staking 
contract and sill being able to operate in T network and earning rewards based
on the liquid T staked. Can be called only by the delegation owner and operator.

==== `unstakeAll(address operator) external onlyOwnerOrOperator(operator)`

Sets cached legacy stake amount to 0, sets the liquid T stake amount to 0 and
withdraws all liquid T from the stake to the owner. Reverts if there is at least one
non-zero authorization. Can be called only by the delegation owner and operator.

=== Keeping information in sync

==== `notifyKeepStakeDiscrepancy(address operator)`

Notifies about the discrepancy between legacy KEEP active stake and amount
cached in T staking contract. Slashes the operator in case the amount cached
is higher than the actual active stake amount in KEEP staking contract. 
Needs to update authorizations of all affected applications and execute an
involuntary authorization decrease on all affected applications.
Can be called by anyone, notifier receives a reward.

Optionally: reward withdrawal can be split into a separate function to protect
against MEV frontrunners. 

==== `notifyNuStakeDiscrepancy(address operator)`

Notifies about the discrepancy between legacy NU active stake and amount
cached in T staking contract. Slashes the operator in case the amount cached
is higher than the actual active stake amount in NU staking contract.
Needs to update authorizations of all affected applications and execute an
involuntary authorization decrease on all affected applications.
Can be called by anyone, notifier receives a reward.

Optionally: reward withdrawal can be split into a separate function to protect
against MEV frontrunners. 

==== `setStakeDiscrepancyPenalty(uint96 penalty, unit256 rewardMultiplier) external onlyGovernance`

Sets the penalty amount for stake discrepancy and reward multiplier for
reporting it. The penalty is seized from the operator account, and 5% of the
penalty, scaled by the multiplier, is given to the notifier. The rest of the
tokens are burned. Can only be called by the governance. See `seize` function.

==== `setNotificationReward(uint96 reward) external onlyGovernance`

Sets reward in T tokens for notification of misbehaviour of one operator.
Can only be called by the governance.

==== `pushNotificationReward(uint96 reward) external`

Transfer some amount of T tokens as reward for notifications of misbehaviour.

==== `withdrawNotificationReward(address recipient, uint96 amount) external onlyGovernance`

Withdraw some amount of T tokens from notifiers treasury. Can only be called by 
the governance.

=== Slashing a stake

==== `slash(uint96 amount, address[] memory operators) external onlyAuthorizedApplication`

Adds operators to the slashing queue along with the amount that should be
slashed from each one of them. Can only be called by an authorized application.

==== `seize(uint96 amount, uint256 rewardMultipier, address notifier, address[] memory operators) external onlyAuthorizedApplication`
	
Adds operators to the slashing queue along with the amount. The notifier will 
receive reward per each operator from notifiers treasury. Can only be called by 
application authorized for all operators in the array.

==== `processSlashing(uint256 count)`

Takes the `count` of queued slashing operations and processes them. Receives 5%
of the slashed amount. Executes `involuntaryAuthorizationDecrease` function on 
each affected application.

=== Auxiliary functions

==== `authorizedStake(address operator, address application) external view returns (uint96)`

Returns the authorized stake amount of the operator for the application.

==== `stakes(address operator) external view returns (uint96 tStake, uint96 keepInTStake, uint96 nuInTStake)`

Returns staked amount of T, Keep and Nu for the specified operator. All values
are in T denomination.

==== `getStartStakingTimestamp(address operator) external view returns (uint256)`

Returns start staking timestamp for T/NU stake. This value is set at most once, 
and only when a stake is created with T or NU tokens. If a stake is created 
from a legacy KEEP stake, this value will remain as zero.

==== `stakedNu(address operator) external view returns (uint256)`

Returns staked amount of NU for the specified operator

==== `rolesOf(address operator) external view returns (address owner, address payable beneficiary, address authorizer)`

Gets the stake owner, the beneficiary and the authorizer for the specified 
operator address.

==== `getApplicationsLength() external view returns (uint256)`

Returns length of application array

==== `getSlashingQueueLength() external view returns (uint256)`

Returns length of slashing queue

==== `getMinStaked(address operator, StakeType stakeTypes) external view returns (uint96)`

Returns minimum possible stake for T, KEEP or NU in T denomination. For example,
if the given operator has 10 T, 20 KEEP, and 30 NU staked, their max authorization
is 40, then `getMinStaked` for that operator returns 0 for KEEP stake type, 10 for
NU stake type, and 0 for T stake type. In other words, minimum staked amount for 
the given stake type is the minimum amount of stake of the given type that needs 
to be preserved in the contract to satisfy the maximum application authorization 
given the amounts of other stake types for that operator.

==== `getAvailableToAuthorize(address operator, address application) external view returns (uint96)`

Returns available amount to authorize for the specified application

=== Application callbacks

==== `authorizationIncreased(address operator, uint96 amount)`

Used by T staking contract to inform the application the the authorized amount
for the given operator increased to the given amount. The application may do any
housekeeping necessary.

==== `authorizationDecreaseRequested(address operator, uint96 amount)`

Used by T staking contract to inform the application that the given operator
requested to decrease the authorization to the given amount. The application
should mark the authorization as pending decrease and respond to the staking
contract with `approveAuthorizationDecrease` at its discretion. It may
happen right away but it also may happen several months later.

==== `involuntaryAuthorizationDecrease(address operator, uint96 amount)`

Used by T staking contract to inform the application the authorization has
been decreased for the given operator to the given amount involuntarily, as
a result of slashing. Lets the application to do any housekeeping neccessary.
Called with 250k gas limit and does not revert the transaction if 
`involuntaryAuthorizationDecrease` call failed.
