name: Code Format Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint and formatting checks
        run: yarn format
